---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ21N20"
  stages:
    Release:
      cfCredentialsId: "deployonbtp"
stages:
  Build:
    source: helloworldui5
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
  Malware Scan:
    malwareExecuteScan: true
  Acceptance:
    cloudFoundryDeploy: false
    npmExecuteEndToEndTests: false
  Compliance:
    sonarExecuteScan: false
  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com/"
    cfOrg: "f5209cd6trial"
    cfSpace: "dev"
    deployType: "standard"
    tmsUpload: false
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
